### ISSUE TITLE
Test `Restate Streaming Connection › should not trigger backpressure for small messages` is flaky

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/sdk-typescript#280]
Just found a flaky test. I never saw it failing locally, only sometimes on CI.

```
FAIL test/protocol_stream.test.ts
  ● Restate Streaming Connection › should not trigger backpressure for small messages

    expect(received).toBeTruthy()

    Received: false

      242 |   await setTimeout(0); // let the callbacks and tasks proceed first
      243 |
    > 244 |   expect(complete).toBeTruthy();
          |                    ^
      245 | }
      246 |
      247 | function roundtripTest(a: Header) {

      at verifyPromiseResolved (test/protocol_stream.test.ts:244:20)
      at Object.<anonymous> (test/protocol_stream.test.ts:151:5)

PASS test/lambda.test.ts
PASS test/promise_combinator_tracker.test.ts
PASS test/awakeable.test.ts
PASS test/complete_awakeable.test.ts
PASS test/utils.test.ts
PASS test/state_keys.test.ts
PASS test/message_coders.test.ts
PASS test/state_machine.test.ts
PASS test/promises.test.ts
PASS test/service_bind.test.ts

Test Suites: 1 failed, 15 passed, 16 total
Tests:       1 failed, 151 passed, 152 total
Snapshots:   0 total
Time:        6.875 s
Error: Process completed with exit code 1.
```

Logs: https://github.com/restatedev/sdk-typescript/actions/runs/8356618021/job/22874055849

**Comment by slinkydeveloper** [comment]
Doesn't seem the case anymore, closing it.
